SELECT ROWID, EMPNO, ENAME
FROM EMP;

SELECT ROWID, DEPTNO, DNAME FROM DEPT;
SELECT ROWID, GRADE FROM SALGRADE;

-- ROWID : ORACLE에서 각 ROW가 생성(INSERT)될 때 마다
-- 만들어서 관리해주는 ID값 => 각 ROW 데이터를 가르키는 주소값
-- 의사컬럼(PSEUDO COLUMN)으로 관리

CREATE TABLE EMP01(EMPNO NUMBER(4), ENAME VARCHAR2(20), SAL NUMBER(7,2));
SELECT * FROM EMP01;

DESC DEPT01;

-- SUBQUERY를 통해서 TABLE생성 가능하며, 이때
-- SELECT에 포함된 데이터(행들)까지 전부 복사됨
CREATE TABLE EMP02
AS
SELECT * FROM EMP; -- SUB QUERY

SELECT * FROM EMP02;

CREATE TABLE EMP03 AS SELECT EMPNO, ENAME FROM EMP;
SELECT * FROM EMP03;

CREATE TABLE EMP04 AS SELECT EMPNO, ENAME, SAL FROM EMP;
SELECT * FROM EMP04;

CREATE TABLE EMP05 AS SELECT * FROM EMP
WHERE DEPTNO=10;
SELECT * FROM EMP05;

-- 테이블 구조만 복사하기. WHERE 1=0 조건은 항상 거짓
CREATE TABLE EMP06 AS SELECT * FROM EMP WHERE 1=0;
SELECT * FROM EMP06;

-- DEPT TABLE의 구조만 생성 => DEPT02
CREATE TABLE DEPT02 AS SELECT * FROM DEPT WHERE 1=0;
DESC DEPT02;
-- 컬럼추가
ALTER TABLE EMP01
ADD(JOB VARCHAR2(9));

ALTER TABLE DEPT02 ADD (DMGR NUMBER(4));
DESC DEPT02;

ALTER TABLE EMP01
MODIFY(JOB VARCHAR2(30));
DESC EMP01;

-- 데이터타입 변경
ALTER TABLE DEPT02
MODIFY (DMGR VARCHAR(10));
DESC DEPT02;

-- 컬럼삭제
ALTER TABLE EMP01
DROP COLUMN JOB;
SELECT * FROM EMP01;

ALTER TABLE DEPT02
DROP COLUMN DMGR;
DESC DEPT02;

ALTER TABLE EMP02
SET UNUSED(JOB);

ALTER TABLE EMP02
DROP UNUSED COLUMNS;

ALTER TABLE EMP02
SET UNUSED(MGR);

DROP TABLE EMP01;
-- TABLE 스키마는 남기고 데이터는 제거
TRUNCATE TABLE EMP02;

RENAME EMP02 TO TEST;

DESC USER_TABLES;
-- 현재 접속중인 USER 정보를 제공
SHOW USER; 
-- 현재 접속중인 user에 등록된 table list를 보여줌
SELECT TABLE_NAME FROM USER_TABLES
ORDER BY TABLE_NAME DESC;
-- ALL_ : 본인 사용자에서 생성된 TABLE과 SYS등 다른 사용자가 나에게
-- 사용권한을 부여한 테이블들을 보여줌
DESC ALL_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;

-- DBA_ 로 시작하는 테이블은 오직 ADMIN(DBA)만 사용가능
SELECT TABLE_NAME, OWNER FROM DBA_TABLES;
