DROP TABLE DEPT02;
DROP TABLE DEPT01;
DROP TABLE TEST;

CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT01
VALUES(40, 'RESEARCH', 'DALLAS');
SELECT * FROM DEPT01;

INSERT INTO DEPT01 (DNAME, DEPTNO, LOC)
VALUES('PURCHASE', 50, 'DALLAS');
SELECT * FROM DEPT01;

DESC DEPT;

-- NULL값을 넣을 때 암시적인 방법
INSERT INTO DEPT01 (DEPTNO, DNAME)
VALUES(60, 'SALES');
-- NULL값을 넣을 때 명시적인 방법 (*권장*)
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC)
VALUES(70, 'SALES1', NULL);
SELECT * FROM DEPT01;
-- '' : NULL값을 넣는다는 의미
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC)
VALUES(80, '', NULL);


CREATE TABLE DEPT02
AS
SELECT * FROM DEPT WHERE 1=0;
SELECT * FROM DEPT02;

INSERT INTO DEPT02
SELECT * FROM DEPT;

-- 다중테이블에 다중행 입력하기
CREATE TABLE EMP_MGR AS SELECT EMPNO, ENAME, MGR FROM EMP
WHERE 1=0;

INSERT ALL INTO EMP_HR VALUES(EMPNO, ENAME, HIREDATE)
INTO EMP_MGR VALUES(EMPNO, ENAME, MGR)
SELECT EMPNO, ENAME, HIREDATE, MGR
FROM EMP
WHERE DEPTNO=20;

SELECT * FROM EMP_MGR;

CREATE TABLE EMP01
AS
SELECT * FROM EMP;

SELECT * FROM EMP01;

UPDATE EMP01
SET DEPTNO=30
WHERE DEPTNO=10;

UPDATE EMP01
SET SAL=SAL*1.1
WHERE SAL >= 3000;

UPDATE EMP01
SET HIREDATE=SYSDATE
WHERE SUBSTR(HIREDATE, 1, 2)='87';

DROP TABLE EMP01;

-- EMP01에서 급여가 3000 이상인 직원들의 급여를 500씩 삭감하시오
UPDATE EMP01
SET SAL=SAL-500
WHERE SAL >=3000;

SELECT * FROM EMP01;