-- 2개 이상의 COLUMN UPDATE
SELECT * FROM EMP01 WHERE ENAME='SCOTT';
UPDATE EMP01
SET DEPTNO=30, JOB='MANAGER'
WHERE ENAME='SCOTT';

UPDATE EMP01
SET HIREDATE = SYSDATE, SAL=50, COMM=4000
WHERE ENAME='SCOTT';

SELECT * FROM DEPT01;
UPDATE DEPT01
SET LOC=(SELECT LOC FROM DEPT01 WHERE DEPTNO=40) WHERE DEPTNO=20;

CREATE TABLE SAM02
AS
SELECT ENAME, SAL, HIREDATE, DEPTNO FROM EMP01;

DESC SAM02;
SELECT * FROM SAM02;

UPDATE SAM02
SET SAL = SAL + 1000
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');

SELECT * FROM DEPT01;
UPDATE DEPT01
SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO=40)
WHERE DEPTNO=20;
-- 이름이 KING인 사람의 SAL과 HIREDATE 복사하라
SELECT * FROM SAM02;
UPDATE SAM02
SET (SAL, HIREDATE) = (SELECT SAL, HIREDATE FROM SAM02 WHERE ENAME='KING');

DELETE FROM DEPT01;
ROLLBACK;
SELECT * FROM DEPT01;

DELETE FROM DEPT01 WHERE DEPTNO=60;
-- LOC가 NULL인 컬럼 삭제
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE LOC IS NULL;

-- emp01 테이블에서 sales 부서 소속 사원들만 삭제 (서브쿼리 이용)
SELECT * FROM emp01;
DELETE FROM emp01
WHERE deptno=(SELECT deptno FROM dept WHERE dname='SALES');

-- sam02 테이블에서 research 부서 소속 사원들만 삭제
SELECT * FROM sam02;
DELETE FROM sam02
where deptno=(select deptno from dept where dname='RESEARCH');

-- merge
DROP TABLE emp01;

CREATE TABLE emp01
AS
SELECT * FROM emp;

create table emp02
AS
SELECT * FROM emp
where job='MANAGER';

UPDATE emp02
SET JOB='TEST';

select * from emp02;

INSERT INTO emp02
values(8000, 'SYJ', 'TOP', 7566, '2009/01/12', 1200, 10, 20);

-- emp02를 이용하여 emp01 병합
MERGE INTO emp01
USING emp02
ON (emp01.empno=emp02.empno)
WHEN MATCHED THEN
UPDATE SET
emp01.ename=emp02.ename,
EMP01.JOB=EMP02.JOB,
EMP01.MGR=EMP02.MGR,
EMP01.HIREDATE=EMP02.HIREDATE,
EMP01.SAL=EMP02.SAL,
EMP01.COMM=EMP02.COMM,
emp01.deptno=emp02.deptno
WHEN NOT MATCHED THEN
INSERT VALUES(emp02.empno, emp02.ename, emp02.JOB, emp02.mgr, emp02.hiredate, emp02.sal, emp02.comm, emp02.deptno);

SELECT * FROM emp01;

